src/chapter6/beans/Post.java
package chapter6.beans;

import java.io.Serializable;
import java.util.Date;

public class Post implements Serializable {
    private static final long serialVersionUID = 1L;

    private int id;
    private String title;
    private String content;
    private String category;
    private int user_id;
    private Date created_at;

    // getter/setterは省略
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public int getUserId() {
        return user_id;
    }

    public void setUserId(int user_id) {
        this.user_id = user_id;
    }

    public Date getCreatedAt() {
        return created_at;
    }

    public void setCreatedAt(Date created_at) {
        this.created_at = created_at;
    }

}

src/chapter6/controller/AdminUserServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import chapter6.beans.User;
import chapter6.service.UserService;


@WebServlet(urlPatterns = { "/adminUser" })
public class AdminUserServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

    	 List<User> users = new UserService().getUsers();

        request.setAttribute("users", users);

        request.getRequestDispatcher("/adminuser.jsp").forward(request, response);
    }
}

src/chapter6/controller/LoginServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.User;
import chapter6.service.LoginService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("login.jsp").forward(request, response);

    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        String account = request.getParameter("loginId");
        String password = request.getParameter("password");

        LoginService loginService = new LoginService();
        List<String> messages = new ArrayList<String>();
        HttpSession session = request.getSession();

        if (isValid(request, messages) == true) {

        User user = loginService.login(account, password);

        if (user != null && user.getState() == 1) {
            messages.add("ログインIDまたはパスワードが誤っています");
            session.setAttribute("loginMessages", messages);
            session.setAttribute("account", account);
            request.getRequestDispatcher("login.jsp").forward(request, response);
        } else if (user != null && user.getState() == 0) {

            session.setAttribute("loginUser", user);
            response.sendRedirect("./");

        } else {
            messages.add("ログインIDまたはパスワードが誤っています");
            session.setAttribute("loginMessages", messages);
            session.setAttribute("account", account);
            request.getRequestDispatcher("login.jsp").forward(request, response);
        }
        } else {
			session.setAttribute("errorMessages", messages);
			session.setAttribute("account", account);
			request.getRequestDispatcher("login.jsp").forward(request, response);
		}
    }

    private boolean isValid(HttpServletRequest request, List<String> messages) {

    	String account = request.getParameter("loginId");
		String password = request.getParameter("password");

		if (StringUtils.isBlank(account) == true || StringUtils.isBlank(password) == true) {
			messages.add("ログインIDまたはパスワードが入力されていません");
		}

    	if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}

    }

}

src/chapter6/controller/SettingServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.Branch;
import chapter6.beans.Position;
import chapter6.beans.User;
import chapter6.exception.NoRowsUpdatedRuntimeException;
import chapter6.service.BranchService;
import chapter6.service.PositionService;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/userEdit" })
public class SettingServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		List<String> messages = new ArrayList<String>();

		HttpSession session = request.getSession();
		User user = (User) session.getAttribute("loginUser");
		request.setAttribute("loginUser", user);

		if (isParam(request, messages) == true) {

			User editUser = new UserService().getUser(Integer.parseInt(request.getParameter("userId")));
			request.setAttribute("editUser", editUser);

			List<Branch> branches = new BranchService().getBranch();
			request.setAttribute("branches", branches);

			List<Position> positions = new PositionService().getPosition();
			request.setAttribute("positions", positions);

			request.getRequestDispatcher("setting.jsp").forward(request, response);
		} else {
			response.sendRedirect("./");
		}
	}

	private boolean isParam(HttpServletRequest request, List<String> messages) {

		HttpSession session = request.getSession();

		if (StringUtils.isBlank(request.getParameter("userId"))==false) {

			String paramId = request.getParameter("userId");

			if (!paramId.matches("^[0-9]*$")) {
				messages.add("不正なパラメータが入力されました。");
				session.setAttribute("messages", messages);
			}else if (new UserService().getUser(Integer.parseInt(request.getParameter("userId"))) == null) {
				messages.add("不正なパラメータが入力されました。");
				session.setAttribute("messages", messages);
			}

		} else if (StringUtils.isBlank(request.getParameter("userId"))==true) {

			messages.add("不正なパラメータが入力されました。");
			session.setAttribute("messages", messages);

		}

		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}


	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {
		List<String> messages = new ArrayList<String>();

		User editUser = getEditUser(request);

		HttpSession session = request.getSession();
		User user = (User) session.getAttribute("loginUser");

		if (isValid(request, messages) == true) {


			try {
				new UserService().update(editUser, user);
				request.setAttribute("loginUser", user);
			} catch (NoRowsUpdatedRuntimeException e) {
				request.setAttribute("editUser", editUser);
				request.getRequestDispatcher("setting.jsp").forward(request, response);
				return;
			}

			request.setAttribute("editUser", editUser);

			response.sendRedirect("adminUser");
		}  else {
			List<Branch> branches = new BranchService().getBranch();
			request.setAttribute("branches", branches);

			List<Position> positions = new PositionService().getPosition();
			request.setAttribute("positions", positions);
			request.setAttribute("errorMessages", messages);
			request.setAttribute("editUser", editUser);
			request.getRequestDispatcher("setting.jsp").forward(request, response);
		}
	}


	private User getEditUser(HttpServletRequest request)
			throws IOException, ServletException {
		HttpSession session = request.getSession();
		User user = (User) session.getAttribute("loginUser");

		User editUser = new User();
		editUser.setId(Integer.parseInt(request.getParameter("id")));
		editUser.setName(request.getParameter("name"));
		editUser.setAccount(request.getParameter("account"));
		editUser.setPassword(request.getParameter("password"));

		if (user.getId() == Integer.parseInt(request.getParameter("id"))) {
			editUser.setBranchId(user.getBranchId());
			editUser.setPositionId(user.getPositionId());
		} else if (user.getId() != Integer.parseInt(request.getParameter("id"))) {
			editUser.setBranchId(Integer.parseInt(request.getParameter("branchId")));
			editUser.setPositionId(Integer.parseInt(request.getParameter("positionId")));
		}
		editUser.setState(Integer.parseInt(request.getParameter("state")));
		return editUser;
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) {

		String account = request.getParameter("account");
		String password = request.getParameter("password");
		String checkPassword = request.getParameter("checkPassword");
		String name = request.getParameter("name");
		int branchId = 0;
		int positionId = 0;

		if (StringUtils.isBlank(request.getParameter("branchId"))==false) {
		branchId = Integer.parseInt(request.getParameter("branchId"));
		}
		if (StringUtils.isBlank(request.getParameter("positionId"))==false) {
		positionId = Integer.parseInt(request.getParameter("positionId"));
		}
		List<String> act = new ArrayList<String>();
		String editUserAccount;
		User edit = null;
		User editUser = null;
		int userId;

		boolean i = false;
		List<User> userList = new UserService().getUsers();

		try {
			edit = getEditUser(request);
		} catch (IOException | ServletException e) {
			// TODO 自動生成された catch ブロック
		}

		userId = edit.getId();
		editUser = new UserService().getUser(userId);
		editUserAccount = editUser.getAccount();

		for (User user :userList) {

			if (!user.getAccount().equals(editUserAccount)) {

				act.add(user.getAccount());
			}
		}

		if (act.contains(account)) {
			i = true;
		}


		if (StringUtils.isBlank(account) == true) {
			messages.add("ログインIDを入力してください");
		} else if (!(account.matches("^[0-9a-zA-Z]+$")) || account.length() > 20 || account.length() < 6) {
			messages.add("ログインIDは半角英数字6～20字で入力してください。");
		} else if (i) {
			messages.add("このログインIDは既に登録されています。");
		}


		if (StringUtils.isBlank(password) == false) {
			if (!password.matches("[-_@+*;:#$%&0-9a-zA-Z]{6,20}$")) {
				messages.add("パスワードは半角英数字6～20字で入力してください。");
			} else if (!checkPassword.equals(password)) {
				messages.add("入力したパスワードと確認用パスワードが一致しません。");
			}
		}

		if (StringUtils.isBlank(name) == true) {
			messages.add("ユーザー名を入力してください");
		}

		if (name.length() > 10) {
			messages.add("ユーザー名は10文字以内で入力してください");
		}

        if (branchId != 0 && positionId != 0) {

		if ((branchId == 1 && positionId == 3) || (branchId == 1 && positionId == 4)) {
			messages.add("本社勤務の場合役職は総務人事担当者または情報管理担当者を選択してください。");
		}


		if ((branchId!=1 && positionId == 1) || (branchId != 1 && positionId == 2)) {
			messages.add("各支店勤務の場合役職は支店長か社員を選択してください。");
		}

        }

		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}

	}

}

src/chapter6/controller/SignUpServlet.java
package chapter6.controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import chapter6.beans.Branch;
import chapter6.beans.Position;
import chapter6.beans.User;
import chapter6.service.BranchService;
import chapter6.service.PositionService;
import chapter6.service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		List<Branch> branches = new BranchService().getBranch();
		request.setAttribute("branches", branches);

		List<Position> positions = new PositionService().getPosition();
		request.setAttribute("positions", positions);

		request.getRequestDispatcher("signup.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		List<String> messages = new ArrayList<String>();

		int branch = Integer.parseInt(request.getParameter("branchId"));

		int position = Integer.parseInt(request.getParameter("positionId"));

		HttpSession session = request.getSession();

		User user = new User();
		user.setName(request.getParameter("name"));
		user.setAccount(request.getParameter("account"));
		user.setPassword(request.getParameter("password"));
		user.setBranchId(branch);
		user.setPositionId(position);

		if (isValid(request, messages) == true) {

			new UserService().register(user);

			response.sendRedirect("adminUser");
		} else {
			String checkPassword = request.getParameter("checkPassword");
			Integer branchId = Integer.parseInt(request.getParameter("branchId"));
			Integer positionId = Integer.parseInt(request.getParameter("positionId"));
			List<Branch> branches = new BranchService().getBranch();
			List<Position> positions = new PositionService().getPosition();
			request.setAttribute("errorMessages", messages);
			request.setAttribute("checkPassword", checkPassword);
			request.setAttribute("branchId", branchId);
			request.setAttribute("positionId", positionId);
			request.setAttribute("positions", positions);
			request.setAttribute("branches", branches);
			request.setAttribute("user", user);
			request.getRequestDispatcher("signup.jsp").forward(request, response);
		}
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) {

		String account = request.getParameter("account");
		String password = request.getParameter("password");
		String checkPassword = request.getParameter("checkPassword");
		String name = request.getParameter("name");
		int branchId = Integer.parseInt(request.getParameter("branchId"));
		int positionId = Integer.parseInt(request.getParameter("positionId"));
		String act = null;
		boolean i = false;

		List<User> userList = new UserService().getUsers();

		for (User user :userList) {
			act = user.getAccount();

			System.out.println(act);
			System.out.println(account);

			if (act.equals(account)) {
				i = true;
			}
		}


		if (StringUtils.isBlank(account) == true) {
			messages.add("ログインIDを入力してください");
		} else if (!(account.matches("^[0-9a-zA-Z]+$")) || account.length() > 20 || account.length() < 6) {
			messages.add("ログインIDは半角英数字6～20字で入力してください。");
		} else if (i) {
			messages.add("このログインIDは既に登録されています。");
		}

		if (StringUtils.isBlank(password) == true) {
			messages.add("パスワードを入力してください");
		} else if (!password.matches("[-_@+*;:#$%&0-9a-zA-Z]{6,20}$")) {
			messages.add("パスワードは半角英数字6～20字で入力してください。");
		} else if (!checkPassword.equals(password)) {
			messages.add("パスワードと確認用パスワードが一致しません。");
		}

		if (StringUtils.isBlank(name) == true) {
			messages.add("ユーザー名を入力してください");
		}

		if (name.length() > 10) {
			messages.add("ユーザー名は10文字以下で入力してください");
		}

		if ((branchId == 1 && positionId == 3) || (branchId == 1 && positionId == 4)) {
			messages.add("本社勤務の場合役職は総務人事担当者または情報管理担当者を選択してください。");
		}

		if ((branchId!=1 && positionId == 1) || (branchId != 1 && positionId == 2)) {
			messages.add("各支店勤務の場合役職は支店長か社員を選択してください。");
		}


		// TODO アカウントが既に利用されていないか、メールアドレスが既に登録されていないかなどの確認も必要
		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}

}

WebContent/adminuser.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<link href="./css/style.css" rel="stylesheet" type="text/css">
<link rel="stylesheet"
	href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet"
	href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script type="text/javascript"
	src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript"
	src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<title>ユーザー管理画面</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link href="./css/style.css" rel="stylesheet" type="text/css">

<script type="text/javascript">
	function stop() {

		// 「OK」時の処理開始 ＋ 確認ダイアログの表示
		if (window.confirm('このアカウントを停止させますか？')) {

			return true;
		}
		// 「OK」時の処理終了

		// 「キャンセル」時の処理開始
		else {

			window.alert('キャンセルされました');

			return false;
		}
		// 「キャンセル」時の処理終了

	}

	function start() {

		// 「OK」時の処理開始 ＋ 確認ダイアログの表示
		if (window.confirm('このアカウントを再開させますか？')) {

			return true;

		}
		// 「OK」時の処理終了

		// 「キャンセル」時の処理開始
		else {

			window.alert('キャンセルされました'); // 警告ダイアログを表示
			return false;
		}
		// 「キャンセル」時の処理終了

	}
</script>

<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>

<script>
	jQuery(document).ready(function() {
		var offset = 100;
		var duration = 500;
		jQuery(window).scroll(function() {
			if (jQuery(this).scrollTop() > offset) {
				jQuery('.pagetop').fadeIn(duration);
			} else {
				jQuery('.pagetop').fadeOut(duration);
			}
		});

		jQuery('.pagetop').click(function(event) {
			event.preventDefault();
			jQuery('html, body').animate({
				scrollTop : 0
			}, duration);
			return false;
		})
	});
</script>


</head>
<body>
	<jsp:include page="/layout/header.jsp" />
	<div class="pageBody">

		<div class="container-fluid">
			<div class="row">
				<div
					class="col-xs-12 col-sm-12 col-md-offset-1 col-md-8 col-lg-offset-1 col-lg-8 col-xl-offset-1 col-xl-8 Body3">

					<div class="users">
						<c:forEach items="${users}" var="user">
							<div class="user">
								<span class="name"><span class="glyphicon glyphicon-user"></span> ID: <c:out value="${user.id}" /></span><br>
								<span class="account">ログインID: <c:out
										value="${user.account}" /></span><br> <span class="name">ユーザー名
									<c:out value="${user.name}" />
								</span><br>
								<%-- <span class="name"><c:out value="${user.password}" /></span> --%>
								<span class="name">配属: <c:out value="${user.branchName}" /></span><br>
								<span class="name">部署・役職: <c:out
										value="${user.positionName}" /></span><br>
										<span>登録日:</span>
								<fmt:formatDate value="${user.createdAt}"
									pattern="yyyy/MM/dd HH:mm:ss" />
								<br>

								<form action="userEdit">
									<input type="hidden" name="userId" value="${user.id}">
									<button type="submit" class="btn userEdit-btn">編集</button>
								</form>

								<c:if test="${loginUser.id != user.id}">
									<c:choose>
										<c:when test="${user.state == 0}">
											<form action="userState" onSubmit="return stop()">
												<input type="hidden" name="userId" value="${user.id}">
												<button type="submit" class="btn stop-btn">アカウント停止</button>
											</form>
										</c:when>
										<c:otherwise>
											<form action="userState" onSubmit="return start()">
												<input type="hidden" name="userId" value="${user.id}">
												<button type="submit" class="btn start-btn">アカウント復活</button>
											</form>
										</c:otherwise>
									</c:choose>
								</c:if>
							</div>
						</c:forEach>
					</div>
					<jsp:include page="/layout/footer.jsp" />
					<div class="pagetop">↑</div>
				</div>
				<jsp:include page="/layout/sidemenu.jsp" />
			</div>
		</div>

	</div>

</body>
</html>

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/xml" prefix="x"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/sql" prefix="sql"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<link rel="stylesheet"
	href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet"
	href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script type="text/javascript"
	src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript"
	src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<title>ログイン</title>

</head>
<body>

	<div class="hidden-xs hidden-sm"
		style="width: 100%; height: 70px; background: #534752; position: fixed; top: 0px; left: 0px; z-index: 10;">
		<div class="header-title"
			style="line-height: 70px; color: #b29a8e; font-family: 'Comic Sans MS'; font-size: 30px; display: inline-block; margin-left: 45px;">
			Internet Discussion Board <span class="glyphicon glyphicon-cutlery"></span>
		</div>
	</div>

	<div class="hidden-md hidden-lg hidden-xl"
		style="width: 100%; height: 100px; background: #534752; position: fixed; top: 0px; left: 0px; z-index: 10;">
		<div class="header2-title"
			style="color: #b29a8e; font-family: 'Comic Sans MS'; font-size: 35px; margin-left: 45px; line-height: 100px;">
			Internet Discussion Board <span class="glyphicon glyphicon-cutlery"></span>
		</div>

	</div>

	<div class="main-contents"
		style="height: 100vh; width: 100%; background: #f3eade; padding-top: 100px; text-align: center; position: relative;">
		<c:if test="${ not empty loginMessages }">

			<c:forEach items="${loginMessages}" var="message">
				<div class="loginMessages" style="border: solid 2px red; width: 50%; height: 100px; margin-left: auto; margin-right: auto;">
					<div style="margin: auto; line-height: 100px;">・<c:out value="${message}" /></div>
				</div>
			</c:forEach>

			<c:remove var="loginMessages" scope="session" />
		</c:if>

		<c:if test="${ not empty errorMessages }">

			<c:forEach items="${errorMessages}" var="message">
				<div class="messages" style=" line-height: 100px; border: solid 2px red; width: 50%; height: 100px; margin-left: auto; margin-right: auto;">
					・<c:out value="${message}" />
				</div>
			</c:forEach>

			<c:remove var="errorMessages" scope="session" />
		</c:if>

		<form action="login" method="post">
			<br /> <label for="LoginId"
				style="font-family: 'Comic Sans MS'; font-size: 25px; color: #7e6356;">Login
				ID</label><br> <input name="loginId" id="loginId" value="${account}"
				style="width: 300px; border-radius: 8px;" /> <br /> <label
				for="password"
				style="font-family: 'Comic Sans MS'; font-size: 25px; color: #7e6356;">Password</label><br>
			<input name="password" type="password" id="password"
				style="width: 300px; border-radius: 8px; margin-bottom: 20px;" /> <br />
			<button type="submit"
				style="width: 300px; border-radius: 8px; font-family: 'Comic Sans MS'; font-size: 25px; background: #534752; color: white;">Login</button>
			<br />

		</form>
		<div class="copyright"
			style="position: absolute; bottom: 0; left: 0; right: 0; margin: auto;">Copyright(c)ShuriSato</div>
	</div>
</body>
</html>

WebContent/post.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>新規投稿</title>
<link href="./css/style.css" rel="stylesheet" type="text/css">
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script type="text/javascript"
	src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript"
	src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<jsp:include page="/layout/header.jsp" />
	<div class="pageBody2">
		<div class="container">
			<div class="row">
				<div
					class="hidden-xs hidden-sm  col-md-offset-2 col-md-8 col-lg-offset-2 col-lg-8 col-xl-offset-2 col-xl-6 Body2">

					<c:if test="${ not empty errorMessages }">
						<div class="errorMessages">
                            <div
									style="text-align: left; height: auto; width: 90%; background: #ffe6ea; margin-left: auto; margin-right: auto; margin-bottom: 20px; padding-left: 10px; line-height: 50px; border: solid 2px red;">
							<c:forEach items="${errorMessages}" var="message">

									・
									<c:out value="${message}" />

								<br>
							</c:forEach>
							</div>

						</div>
						<c:remove var="errorMessages" scope="session" />
					</c:if>

					<div class="form-area">
						<form action="newPost" method="post">
							<br /> <input name="title" id="title" placeholder="タイトル"
								value="${post.title}" /> <br /> <input name="category"
								placeholder="カテゴリー" id="category" value="${post.category}" /> <br />
							<textarea name="content" cols="100" rows="5" class="content-box"
								placeholder="本文" id="content">${post.content}</textarea>
							<br />
							<button class="btn post-btn" type="submit">
								投稿する <span class="glyphicon glyphicon-pencil"></span>
							</button>
						</form>
					</div>
				</div>

				<div class="hidden-md hidden-lg hidden-xl col-xs-12 col-sm-12 Body1">

					<c:if test="${ not empty errorMessages }">
						<div class="errorMessages">
							<ul>
								<c:forEach items="${errorMessages}" var="message">
									<li><c:out value="${message}" />
								</c:forEach>
							</ul>
						</div>
						<c:remove var="errorMessages" scope="session" />
					</c:if>

					<div class="form-area">
						<c:out value="${post}" />
						<form action="newPost" method="post">
							<br /> <input name="title" id="rs-title" placeholder="件名"
								value="${post.title}" /> <br /> <input name="category"
								placeholder="カテゴリー" id="rs-category" value="${post.category}" />
							<br />
							<textarea name="content" cols="100" rows="5" class="content-box"
								placeholder="本文" id="rs-content">${post.content}</textarea>

							<br />
							<button class="btn rs-post-btn" type="submit">
								投稿する <span class="glyphicon glyphicon-pencil"></span>
							</button>
						</form>
					</div>
				</div>

			</div>
		</div>
		<jsp:include page="/layout/footer.jsp" />
	</div>
</body>
</html>